# Generated by Django 5.1 on 2024-08-15 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=250)),
                ('file_type', models.CharField(max_length=250)),
                ('account', models.CharField(max_length=250)),
                ('import_date', models.DateField()),
                ('max_date', models.DateField()),
                ('min_date', models.DateField()),
                ('checksum', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('inout', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('cycle', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=250)),
                ('debitor', models.CharField(max_length=250)),
                ('verwendung', models.CharField(max_length=250)),
                ('konto', models.CharField(max_length=250)),
                ('debitor_id', models.CharField(max_length=250)),
                ('mandats_ref', models.CharField(max_length=250)),
                ('customer_ref', models.CharField(max_length=250)),
                ('src_konto', models.CharField(max_length=250)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('properties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='home.property')),
            ],
        ),
    ]
