# Generated by Django 5.1 on 2024-08-16 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_transaction_customer_ref_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='properties',
        ),
        migrations.AddField(
            model_name='transaction',
            name='properties',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='home.property'),
        ),
    ]
