site_name: BUGAL

# setting up the theme for documentation
theme:
  name: "material"

# to generate documentation from docstrings from code
plugins:
  - mkdocstrings

# include new chapter / md files
nav:
  - index.md
  - ug.md
  - releasenotes.md
  - req/req.md


