# Generated by Django 4.2.17 on 2024-12-29 17:53

from django.db import migrations, models
import finapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EUR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=50)),
                ('inout', models.CharField(max_length=5)),
                ('cycle', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly')], default=('monthly', 'monthly'), max_length=50)),
                ('ROI', models.TextField()),
                ('note', models.TextField()),
                ('daily', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weekly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yearly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slug', models.SlugField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=10)),
                ('account', models.CharField(max_length=100)),
                ('max_date', models.DateField()),
                ('min_date', models.DateField()),
                ('hash', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdate', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('debitor', models.CharField(max_length=100)),
                ('verwendung', models.CharField(max_length=300)),
                ('konto', models.CharField(max_length=100, validators=[finapp.models.validate_konto])),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debitor_id', models.CharField(max_length=100)),
                ('mandats_ref', models.CharField(max_length=100)),
                ('customer_ref', models.CharField(max_length=100)),
                ('src_konto', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=300)),
                ('hash', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddConstraint(
            model_name='transactions',
            constraint=models.UniqueConstraint(fields=('hash',), name='unique_transaction_hash'),
        ),
        migrations.AddConstraint(
            model_name='history',
            constraint=models.UniqueConstraint(fields=('hash',), name='unique_history_hash'),
        ),
    ]
