# Generated by Django 4.2.17 on 2024-12-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eur',
            name='priority',
            field=models.CharField(default='TBD', max_length=50),
        ),
    ]
