# Generated by Django 4.2.17 on 2024-12-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finapp', '0002_eur_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eur',
            name='category',
            field=models.CharField(default='TBD', max_length=50),
        ),
    ]
