[bugal]
label = "bugal"

# Configure the file locations absolute path
[[bugal.src]]
# genral source path
srcpath = "d:/projects/910_prProjects/bugal/bugal_p"
# csv file to be imported
csv_file = "d:/projects/910_prProjects/bugal/bugal_p/1001670080-2021.csv"
# db file to be used
db_file = "d:/projects/910_prProjects/bugal/bugal_p/import_2.db"
# zip file to be used
zip_file = "d:/projects/910_prProjects/bugal/bugal_p/archive_1.zip"
# excel file to be used
xls_file = "d:/projects/910_prProjects/bugal/bugal_p/bugal_view_1.xlsx"

# Configure a test run with "True" or real run with "False"
[[bugal.run]]
TEST = "True"

[[bugal.test]]
# genral source path
srcpath = "d:/projects/910_prProjects/bugal/bugal_p"
# csv file to be imported
csv_file = "d:/projects/910_prProjects/bugal/tests/20-10-2023_Umsatzliste_Girokonto_DE90120300001001670080.csv"
# db file to be used
db_file = "d:/projects/910_prProjects/bugal/tests/fixtures/import_2.db"
# zip file to be used
zip_file = "d:/projects/910_prProjects/bugal/tests/fixtures/archive_1.zip"
# excel file to be used
xls_file = "d:/projects/910_prProjects/bugal/tests/fixtures/bugal_view_1.xlsx"


# configuration of the source file type [BETA, CLASSIC]
[[bugal.type]]
type = "BETA"
