# Generated by Django 6.0.4 on 2026-05-05 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_md5', models.CharField(max_length=32, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('konto', models.CharField(max_length=100)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField(default=0)),
                ('min_date', models.DateField(blank=True, null=True)),
                ('max_date', models.DateField(blank=True, null=True)),
                ('duplicate_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Import',
                'verbose_name_plural': 'Importe',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='transactions.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['parent__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FilterRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('debitor_contains', models.CharField(blank=True, max_length=255)),
                ('verwendung_contains', models.CharField(blank=True, max_length=255)),
                ('art', models.CharField(blank=True, choices=[('FIX', 'Fix'), ('FLEX', 'Flex')], max_length=10)),
                ('prioritaet', models.CharField(blank=True, choices=[('Familie', 'Familie'), ('Kinder', 'Kinder'), ('Waldemar', 'Waldemar'), ('Nastja', 'Nastja'), ('Uljana', 'Uljana'), ('Mischa', 'Mischa')], max_length=20)),
                ('intervall', models.CharField(blank=True, choices=[('einmalig', 'Einmalig'), ('wöchentlich', 'Wöchentlich'), ('monatlich', 'Monatlich'), ('quartal', 'Quartal'), ('halbjährlich', 'Halbjährlich'), ('jährlich', 'Jährlich'), ('abgelaufen', 'Abgelaufen'), ('geplant', 'Geplant')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('date', models.DateField()),
                ('status', models.CharField(blank=True, max_length=50)),
                ('debitor', models.CharField(max_length=255)),
                ('verwendung', models.TextField(blank=True)),
                ('target_konto', models.CharField(blank=True, max_length=100)),
                ('src_konto', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('debitor_id', models.CharField(blank=True, max_length=100)),
                ('mandats_ref', models.CharField(blank=True, max_length=100)),
                ('customer_ref', models.CharField(blank=True, max_length=100)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('import_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.importhistory')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_by', models.CharField(choices=[('auto', 'Automatisch'), ('manual', 'Manuell')], default='auto', max_length=10)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.category')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='transactions.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(blank=True, choices=[('FIX', 'Fix'), ('FLEX', 'Flex')], max_length=10)),
                ('prioritaet', models.CharField(blank=True, choices=[('Familie', 'Familie'), ('Kinder', 'Kinder'), ('Waldemar', 'Waldemar'), ('Nastja', 'Nastja'), ('Uljana', 'Uljana'), ('Mischa', 'Mischa')], max_length=20)),
                ('intervall', models.CharField(blank=True, choices=[('einmalig', 'Einmalig'), ('wöchentlich', 'Wöchentlich'), ('monatlich', 'Monatlich'), ('quartal', 'Quartal'), ('halbjährlich', 'Halbjährlich'), ('jährlich', 'Jährlich'), ('abgelaufen', 'Abgelaufen'), ('geplant', 'Geplant')], max_length=20)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.filterrule')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='transactions.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debitor', models.CharField(max_length=255)),
                ('next_expected_date', models.DateField()),
                ('avg_interval_days', models.IntegerField()),
                ('last_occurrence', models.DateField()),
                ('confidence', models.FloatField()),
                ('predicted_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.category')),
            ],
            options={
                'ordering': ['next_expected_date'],
                'unique_together': {('debitor', 'category')},
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date'], name='transaction_date_ad8c94_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['debitor'], name='transaction_debitor_81a7e4_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['value'], name='transaction_value_4fd547_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transactioncategory',
            unique_together={('transaction', 'category')},
        ),
    ]
