# Generated by Django 6.0.4 on 2026-08-27 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transactioninfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='import_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.importhistory'),
        ),
    ]
