# Generated by Django 6.0.4 on 2026-08-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_import_cascade_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='EuerPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hint', models.TextField(blank=True, default='')),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transactions', models.ManyToManyField(blank=True, related_name='euer_positions', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'EÜR-Position',
                'verbose_name_plural': 'EÜR-Positionen',
                'ordering': ['name'],
                'unique_together': {('name', 'year')},
            },
        ),
    ]
