# Generated by Django 6.0.4 on 2026-08-27 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_euer_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='euerposition',
            name='art',
            field=models.CharField(blank=True, choices=[('FIX', 'Fix'), ('FLEX', 'Flex')], max_length=10),
        ),
        migrations.AddField(
            model_name='euerposition',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='euer_positions', to='transactions.category'),
        ),
        migrations.AddField(
            model_name='euerposition',
            name='intervall',
            field=models.CharField(blank=True, choices=[('einmalig', 'Einmalig'), ('wöchentlich', 'Wöchentlich'), ('monatlich', 'Monatlich'), ('quartal', 'Quartal'), ('halbjährlich', 'Halbjährlich'), ('jährlich', 'Jährlich'), ('abgelaufen', 'Abgelaufen'), ('geplant', 'Geplant')], max_length=20),
        ),
        migrations.AddField(
            model_name='euerposition',
            name='prioritaet',
            field=models.CharField(blank=True, choices=[('Familie', 'Familie'), ('Kinder', 'Kinder'), ('Waldemar', 'Waldemar'), ('Nastja', 'Nastja'), ('Uljana', 'Uljana'), ('Mischa', 'Mischa')], max_length=20),
        ),
    ]
