# Generated by Django 6.0.4 on 2026-08-27 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_euer_position_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investitionsobjekt', models.CharField(max_length=200)),
                ('datum', models.DateField(blank=True, null=True)),
                ('prioritaet', models.CharField(blank=True, choices=[('Familie', 'Familie'), ('Kinder', 'Kinder'), ('Waldemar', 'Waldemar'), ('Nastja', 'Nastja'), ('Uljana', 'Uljana'), ('Mischa', 'Mischa')], max_length=20)),
                ('nutzniesser', models.CharField(blank=True, choices=[('Familie', 'Familie'), ('Kinder', 'Kinder'), ('Waldemar', 'Waldemar'), ('Nastja', 'Nastja'), ('Uljana', 'Uljana'), ('Mischa', 'Mischa')], max_length=20, verbose_name='Wem nützt es?')),
                ('roi', models.TextField(blank=True, verbose_name='ROI')),
                ('aktuelle_loesung', models.TextField(blank=True)),
                ('nutzung_ab', models.DateField(blank=True, null=True, verbose_name='Ab wann soll es genutzt werden?')),
                ('intervall', models.CharField(blank=True, choices=[('einmalig', 'Einmalig'), ('wöchentlich', 'Wöchentlich'), ('monatlich', 'Monatlich'), ('quartal', 'Quartal'), ('halbjährlich', 'Halbjährlich'), ('jährlich', 'Jährlich'), ('abgelaufen', 'Abgelaufen'), ('geplant', 'Geplant')], max_length=20, verbose_name='Wie oft wird es genutzt')),
                ('zeitaufwand_min', models.DurationField(blank=True, null=True, verbose_name='Zeitaufwand je Nutzung min')),
                ('zeitaufwand_max', models.DurationField(blank=True, null=True, verbose_name='Zeitaufwand je Nutzung max')),
                ('nutzungsdauer_min', models.CharField(blank=True, max_length=100, verbose_name='Wie lange genutzt min')),
                ('nutzungsdauer_max', models.CharField(blank=True, max_length=100, verbose_name='Wie lange genutzt max')),
                ('diy_workaround', models.TextField(blank=True, verbose_name='DIY Workaround')),
                ('gebrauchtkauf_status', models.CharField(blank=True, choices=[('ja', 'Ja'), ('nein', 'Nein')], max_length=10, verbose_name='Gebrauchtkauf')),
                ('gebrauchtkauf_begruendung', models.TextField(blank=True)),
                ('mietmoeglichkeit', models.TextField(blank=True, verbose_name='Mietmöglichkeit')),
                ('preis_entwicklung', models.CharField(blank=True, max_length=200, verbose_name='voraussichtliche Preisentwicklung')),
                ('folgeanschaffungen', models.TextField(blank=True, verbose_name='Folgeanschaffungen')),
                ('mietkosten_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mietkosten_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('anschaffungspreis_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('anschaffungspreis_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('folgeanschaffungen_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('folgeanschaffungen_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('inbetriebnahme_kosten_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Inbetriebnahme Kosten min')),
                ('inbetriebnahme_kosten_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Inbetriebnahme Kosten max')),
                ('inbetriebnahme_zeit_min', models.DurationField(blank=True, null=True, verbose_name='Inbetriebnahme Zeit min')),
                ('inbetriebnahme_zeit_max', models.DurationField(blank=True, null=True, verbose_name='Inbetriebnahme Zeit max')),
                ('betriebskosten_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('betriebskosten_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('instandhaltung_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Instandhaltungskosten min')),
                ('instandhaltung_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Instandhaltungskosten max')),
                ('reinigung_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Reinigung min')),
                ('reinigung_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Reinigung max')),
                ('versicherung_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Versicherung min')),
                ('versicherung_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Versicherung max')),
                ('reparatur_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Reparatur min')),
                ('reparatur_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Reparatur max')),
                ('entsorgung_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Entsorgung min')),
                ('entsorgung_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Entsorgung max')),
                ('wiederverkauf_prozent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Wiederverkauf % vom Anschaffungspreis')),
                ('letzte_ueberpruefung', models.DateField(blank=True, null=True, verbose_name='letzte Überprüfung dieser Angaben')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('euer_position', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment', to='transactions.euerposition')),
                ('kategorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='transactions.category')),
            ],
            options={
                'verbose_name': 'Geplantes Investment',
                'verbose_name_plural': 'Geplante Investments',
                'ordering': ['-datum', 'investitionsobjekt'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('geplant', 'Geplant'), ('geprueft', 'Geprüft'), ('genehmigt', 'Genehmigt'), ('abgelehnt', 'Abgelehnt'), ('verschoben', 'Verschoben'), ('umgesetzt', 'Umgesetzt')], default='geplant', max_length=20)),
                ('datum', models.DateField(blank=True, null=True)),
                ('begruendung', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entscheidungen', to='transactions.plannedinvestment')),
            ],
            options={
                'verbose_name': 'Investmententscheidung',
                'verbose_name_plural': 'Investmententscheidungen',
                'ordering': ['-datum', '-created_at'],
            },
        ),
    ]
